---
new_page_extension: md
auto_deploy: false
admin_path: static/admin
webhook_url: https://api.stackbit.com/project/5d3f4322c7e1cd00130cd5b6/webhook/forestry
sections:
- type: heading
  label: Posts & Pages
- type: directory
  path: src/pages/posts
  label: Post
  create: all
  match: "**/*"
  templates:
  - post
- type: directory
  path: src/pages
  label: Page
  create: all
  match: "**/*"
  exclude: "{posts/**,index.md,contact.md}"
  templates:
  - page
- type: document
  path: src/pages/index.md
  label: Home
  templates:
  - home
- type: document
  path: src/pages/contact.md
  label: Contact
  templates:
  - contact
- type: heading
  label: Config
- type: document
  path: site-metadata.json
  label: Global Site Config
  templates:
  - config
- type: document
  path: src/data/author.json
  label: Author
  templates:
  - author
- type: document
  path: src/data/social.json
  label: Social Links
  templates:
  - social
- type: document
  path: src/data/subscribe.json
  label: Subscribe
  templates:
  - subscribe
upload_dir: static/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: 
file_template: ":year:-:month:-:filename:"
build:
  preview_command: gatsby build
  publish_command: gatsby build
  preview_output_directory: public
  output_directory: public
  instant_preview_command: npm run forestry:preview
  install_dependencies_command: npm install
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv"
